STL_DIR=tl
AMF_DIR=amf
IMG_DIR=img
SRC_DIR=printplate
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../
OUTPUT_FOLDER=Manufacturing/$(PRINTER)
NAME_PREFIX=TFSLOT01
PROCESSOR3D_PARAM=--force --no_stl

include ../../utils/Makefile
