name: Build printable files

on:
  push:
    paths:
      - '**.scad'
      - '**.ini'
      - '**.yml'
    branches:
     - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        printer: [mini_prusaslicer_quality]
        #printer: [mini_prusaslicer_quality, mini, edee, mlab3d]
    env:
      OPENSCAD_BIN: xvfb-run --auto-servernum ~/OpenSCAD.AppImage
      SLIC3R_BIN: prusa-slicer
      PRINTER: ${{ matrix.printer }}
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    # - uses: hmarr/debug-action@v2

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUBPAT }}
        submodules: recursive

    - name: Install requirements
      run: |
        lsb_release -a
        # sudo apt-get update
        sudo apt-get install prusa-slicer 
        # sudo apt-get install libglu1-mesa libgtk2.0-0 libpangox-1.0-0
        # wget --progress=bar:force:noscroll https://dl.slic3r.org/linux/Slic3r-1.3.0-x86_64.AppImage -O ~/Slic3r.AppImage
        # chmod +x ~/Slic3r.AppImage
        wget --progress=bar:force:noscroll https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.4.0-beta4/PrusaSlicer-2.4.0-beta4+linux-x64-202112110942.AppImage -O ~/PrusaSlicer.AppImage
        #chmod +x ~/PrusaSlicer.AppImage
        #~/PrusaSlicer.AppImage --help
        wget --progress=bar:force:noscroll https://files.openscad.org/snapshots/OpenSCAD-2022.02.13.ai10916-x86_64.AppImage -O ~/OpenSCAD.AppImage
        chmod +x ~/OpenSCAD.AppImage
        sudo apt-get install libc-bin python3-setuptools xvfb
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install stlsort lxml
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/yagv@a541869d11d3c094f1d7a3ed4d3c0c30489398e9
        sudo python3 -m pip install git+https://${{ secrets.AUTH_USER }}:${{ secrets.GITHUBPAT }}@github.com/ThunderFly-aerospace/processor3D.git@PrusaSlicer
        # export SLIC3R_BIN=~/PrusaSlicer.AppImage

    - name: Make
      run: |
        mkdir -p Manufacturing/${{matrix.printer}}/amf 2> /dev/null
        mkdir -p Manufacturing/${{matrix.printer}}/json 2> /dev/null
        mkdir -p Manufacturing/${{matrix.printer}}/stl 2> /dev/null
        mkdir -p Manufacturing/${{matrix.printer}}/png 2> /dev/null
        mkdir -p Manufacturing/${{matrix.printer}}/gcode 2> /dev/null
        tree /home/runner/work/TFSLOT01/TFSLOT01
        cd CAD/src/; make
        tree /home/runner/work/TFSLOT01/TFSLOT01
        
    - name: test
      run: |
        tail /home/runner/work/TFSLOT01/TFSLOT01/Manufacturing/mini_prusaslicer_quality/amf/tfslot_888_1001.amf
        tail /home/runner/work/TFSLOT01/TFSLOT01/CAD/slicing/default.ini
        prusa-slicer --export-gcode -o /home/runner/work/TFSLOT01/TFSLOT01/Manufacturing/mini_prusaslicer_quality/gcode/TFSLOT01_tfslot_888_1003.gcode --load /home/runner/work/TFSLOT01/TFSLOT01/CAD/slicing/default.ini /home/runner/work/TFSLOT01/TFSLOT01/Manufacturing/mini_prusaslicer_quality/amf/tfslot_888_1003.amf
        #prusa-slicer --export-gcode -o /home/runner/work/TFSLOT01/TFSLOT01/Manufacturing/mini_prusaslicer_quality/gcode/TFSLOT01_tfslot_888_1002.gcode --load /home/runner/work/TFSLOT01/TFSLOT01/CAD/slicing/default.ini /home/runner/work/TFSLOT01/TFSLOT01/Manufacturing/mini_prusaslicer_quality/amf/tfslot_888_1002.amf
        
    - name: Upload a Manufactunirg data
      uses: actions/upload-artifact@v2.2.2
      with:
        name: 'Manufacture ${{matrix.printer}}'
        path: 'Manufacturing/${{matrix.printer}}'


    - name: Upload a AMF Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: 'render_amf'
        path: './**/*.amf'

    - uses: FranzDiebold/github-env-vars-action@v2
    
    

    - name: Upload gcodes
      uses:  MLAB-project/push-generated-file@master
      with:
        source_file_path: 'CAD/gcode'
        destination_folder: 'gcode'
        destination_repo: 'ThunderFly-aerospace/gcodes'
        target_branch:  ${{env.CI_REPOSITORY}}/${{env.CI_REF_NAME}}/${{matrix.printer}}
        token: ${{ secrets.GITHUBPAT }}

#     - name: Upload images
#       uses:  MLAB-project/push-generated-file@master
#       with:
#         source_file_path: 'CAD/img'
#         destination_folder: 'png'
#         destination_repo: 'ThunderFly-aerospace/gcodes'
#         target_branch:  TF-G2/${{github.ref}}/${{matrix.printer}}
#         token: ${{ secrets.GITHUBPAT }}
    
 #   - name: pull
 #     run: git pull
        
 #   - name: publish to git        
 #     uses: stefanzweifel/git-auto-commit-action@v4
 #     with:
 #       commit_message: Automatic commit from workflow
 #       commit_user_name: TFbot
        
